name: CI with Docker and PyTorch

on:
  push:
    branches: [ main ]  # プッシュ時にCIをトリガー
  pull_request:
    branches:
      - main  # PR作成時にCIをトリガー

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actionsのベース環境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # リポジトリコードをチェックアウト

      - name: Set up Docker without GPU
        run: |
          # 通常のDockerを使ってコンテナを実行（非インタラクティブモード）
          sudo docker run --rm \
            -v $PWD:/workspace \
            pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime bash -c "
              # コンテナ内で依存関係をインストール
              pip install --no-cache-dir \
                qiskit==2.0.2 \
                pytest==8.3.5 \
                matplotlib \
                torchvision==0.16.0 \
                tqdm \
                pylatexenc \
                qiskit-aer \
                xformers \
                debugpy \
                qiskit-machine-learning &&
              # テストを実行
              pytest
            "
